VARIANCE

In [12]:
def variance(data):
    # Number of observations
    n = len(data)
    # Mean of the data
    mean = sum(data) / n
    # Square deviations
    deviations = [(x - mean) ** 2 for x in data]
    # Variance
    Variance = sum(deviations) / n
    return variance

In [13]:
import numpy as np

def covariance(x, y):
    assert len(x) == len(y)
    n = len(x)
    mean_x = np.mean(x)
    mean_y = np.mean(y)
    cov = np.sum((x - mean_x) * (y - mean_y)) / (n - 1)
    return cov

# Example data
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

# Calculating covariance
covariance_value = covariance(x, y)
print("Covariance:", covariance_value)


Covariance: 5.0


In [15]:
import numpy as np

def correlation_matrix(data):
    # Calculate the correlation matrix
    corr_matrix = np.corrcoef(data)
    return corr_matrix

# Example data
data = np.array([[1, 2, 3], [6, 5, 4], [7, 8, 9]])

# Calculating the correlation matrix
correlation_matrix = correlation_matrix(data)
print("Correlation Matrix:")
print(correlation_matrix)


Correlation Matrix:
[[ 1. -1.  1.]
 [-1.  1. -1.]
 [ 1. -1.  1.]]


In [16]:
import numpy as np

def covariance_matrix(data):
# Calculate the covariance matrix
    cov_matrix = np.cov(data, rowvar=False)
    return cov_matrix

# Example data
data = np.array([[9, 6, 3], [1, 2, 3], [2, 4, 8]])

# Calculating the covariance matrix
covariance_mat = covariance_matrix(data)
print("Covariance Matrix:")
print(covariance_mat)


Covariance Matrix:
[[19.          8.         -5.        ]
 [ 8.          4.          0.        ]
 [-5.          0.          8.33333333]]


In [19]:
import numpy as np

# Example matrix
matrix = np.array([[1, 2], [3, 4]])

# Calculating eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

# Printing the eigenvalues
print("Eigenvalues:")
print(eigenvalues)

# Printing the eigenvectors
print("Eigenvectors:")
print(eigenvectors)

Eigenvalues:
[-0.37228132  5.37228132]
Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
